#!/bin/bash

fullname=$1
filename="${fullname%.*}"
directory="${fullname%/*}"

mkdir -p foo/bar
rm -f $1.ll
../latc_llvm.bin < $1 > $filename.ll

if [ -f $filename.ll ]; then
  llvm-as -o $filename.bc.part $filename.ll
  llvm-link -o $filename.bc $filename.bc.part lib/runtime.bc 
fi
