/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "LLVMBuilder.h"
#include "LLVMProgramPrinter.h"

int main(int argc, char ** argv) {
  Program *parse_tree = pProgram(stdin);
  if (parse_tree) { 
    LlvmBuilder *b = new LlvmBuilder();
    LLVMProgram llvmProgram = b->compile(parse_tree); 
    LLVMProgramPrinter::print(llvmProgram);
    return 0;
  }
  return 1;
}
